# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
    docker:
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  install-dependencies:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm install"

  deploy-to-netlify:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: "Build Docker image"
          command: "docker build -t react-vite-app:latest ."
      - run:
          name: "Install dependencies"
          command: "npm install"
      - run:
          name: "Build project"
          command: "npm run build"
      - run:
          name: "Install Netlify CLI"
          command: "npm install -g netlify-cli"
      - run:
          name: "Deploy to Netlify"
          command: "netlify deploy --prod --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID"

workflows:
  main-workflow:
    jobs:
      - say-hello
      - install-dependencies
      - deploy-to-netlify:
          requires:
            - install-dependencies
